### ISSUE TITLE
Creating own user repository plugin

### ISSUE THREAD

**Issue by fabreim** [Communote/communote-server#26]
Hi!

We are trying to implement our own user repository plugin. 
We managed to get the plugin loaded and shown under the integration tab, but when we try to activate it, it is telling us that the plugin is not configured properly.

We implemented a UserRepository which extends AbstractExternalUserRepository, a RepoConfiguration extending ExternalSystemConfiguration and an Activator extending BundleActivator. 
In the Activator we are creating a new UserRepo with the RepoConfiguration and registering it via the UserService.

Could you give us some advice?

Thank you in advance!

**Comment by rwi** [comment]
External user repos defined in plugins can't currently be made the primary authentication system (i guess that's what you mean with 'trying to activate'). This part needs some refactoring to make more flexible.
But if you can give us some more detail about the external repository and how you want to use it we may find a way around this limitation.

**Comment by fabreim** [comment]
Our user repository is basically a database and we want to use/synchronize it with communote.
We are relatively free in configuring/changing the format of the users and the way of getting them into Communote, but we can't use LDAP. That's why we tried to create the plugin. 
If synchronisation  is not possible, it would also be fine if there is a way to create/delete users in communote via an API!
Thank you for helping us!

**Comment by rwi** [comment]
To get your users into Communote you can add them during authentication. This is how the LDAP integration does it and  would work as follows: if a user logs in via the login page, your plugin checks whether the credentials are valid and if so, instructs the UserService to create or update the user. The details of the user are loaded from your UserRepository implementation.

For this to work with a pure plugin solution you will first have to make sure that Communote uses the so called 'flexible' repository mode. This mode allows querying an external user repository during authentication which is not the 'primary' one. The form of the Integration Overview page in Communote's administration section has a radio button to enable this mode. Moreover, your repository needs to provide a first name, a last name and a unique email address for every user.

Now you have to extend your plugin with a [CommunoteAuthenticationProvider](https://github.com/Communote/communote-server/blob/master/communote/persistence/src/main/java/com/communote/server/core/security/CommunoteAuthenticationProvider.java) which takes care of checking the credentials. The AuthenticationProvider should support the org.springframework.security.authentication.UsernamePasswordAuthenticationToken because instances of this class will be created by Spring security when submitting the login form. Depending on how you implement the authentication check you could inherit from [BaseCommunoteAuthenticationProvider](https://github.com/Communote/communote-server/blob/master/communote/persistence/src/main/java/com/communote/server/core/security/authentication/BaseCommunoteAuthenticationProvider.java) or its subclass [ExternalAuthenticationProvider](https://github.com/Communote/communote-server/blob/master/communote/persistence/src/main/java/com/communote/server/core/security/authentication/ExternalAuthenticationProvider.java). The important step which creates or updates the user in Communote can be found in the ExternalAuthenticationProvider#getUser Method. The UserIdentification which is passed to the UserService needs to have the same externalSystemId as your UserRepository.
In case you are not inheriting from BaseCommunoteAuthenticationProvider you should copy its doAdditionalAuthenticationChecks method as it provides some additional features like testing if the account was locked because of several failed login attempts.
To let Communote find your CommunoteAuthenticationProvider you have to register it to the AuthenticationProviderManagement service. As an alternative to a manual registration you can add IPojo's Component, Instantiate and Provides annotations to the provider to get automatic registration (see [RemoteUserAuthenticationProvider](https://github.com/Communote/communote-plugin-remote-user-authentication/blob/master/src/main/java/com/communote/plugin/remoteuser/RemoteUserAuthenticationProvider.java) for an example).

If a user is removed from your repository, the next login will fail. In case this is not enough and the user should also be removed from Communote, you could add a com.communote.server.api.core.task.TaskHandler to your plugin which takes care of this (example of registering such a task handler can be found in [ActivityBaseActivator](https://github.com/Communote/communote-server/blob/master/communote/plugins/communote-activity-base-plugin/src/main/java/com/communote/plugins/activity/base/ActivityBaseActivator.java)). This task could also synchronize all users if automatic creation/update on login is too late.

**Comment by fabreim** [comment]
Hi!

Thank you very much for your detailed explanation and extensive support! We tried to implement a solution but in the end it happened to be possible to use LDAP as well and we will use it now instead.

Thank you for your time and effort nonetheless!
