### ISSUE TITLE
Content API or outgoing hook

### ISSUE THREAD

**Issue by datenwort** [Communote/communote-server#40]
Hi,

I tried to add an external communication channel which should listen to the content on a specific topic. Maybe I am blind but I cannot find an introduction how to get the content of a topic? Is therer currently a possibility?

**Comment by datenwort** [comment]
So I was blind. Found the ```.../timelineNotes/``` API. But is there a way to implement a hook?

**Comment by scrobbleme** [comment]
What hook do you mean? Do you have an example?

**Comment by datenwort** [comment]
Outgoing webhooks are mostly used to react on something. In [Wekan](https://github.com/wekan/wekan/pull/1119) for example a notification is send via this webhook if a card is changed, moved or something else. The listener then can analyse the change and react (e.g. refresh the burn down chart, adding a new requirement to the requirements document).
In [Slack](https://api.slack.com/custom-integrations/outgoing-webhooks) is also a possibility to use this.

Reason is for example to react on communication with a users (e.g. bots) or in a room. So you send a note in a room and the listener (bot, ai) analyse the text and react on it (e.g. send back an answer)

Hope this was understandable.

**Comment by rwi** [comment]
There is a hook which allows you do something after a note was created or updated, but it's a bit more low-level (and because of this more powerful 😉 ) than in your examples. What you have to do is something like this:

- Use the Communote Maven Archetype to create a Communote plugin as described in section 2.1.1 of the [How to Write a plugin](http://communote.github.io/doc/dev_how_plugin.html) tutorial.
- In your plugin create a class which implements the interface [NoteStoringPostProcessor](https://github.com/Communote/communote-server/blob/master/communote/api/src/main/java/com/communote/server/api/core/note/processor/NoteStoringPostProcessor.java)
  - Implementations of this interface will be called whenever a note is created or updated.
  - You can use the `process` method to decide whether you want to react on the creation or update of the provided note and for instance check the content for some trigger words, look for mentioned users or maybe check that the topic (aka blog or room) has a certain title. If the note should be handled return `true`.
  - If the `process` method returns true, the method `processAsynchronously` will be called and allows you to do whatever you like. To send an HTTP request to some URL you can use the [HttpClient library](https://hc.apache.org/httpcomponents-client-4.3.x/tutorial/html/index.html) which is bundled in Communote.
    - ℹ️ When using the HttpClient library in your processor you'll have to add it as a provided Maven dependency to the pom.xml which is created by the Maven Archetype.
    - In case you want to send some additional data about the note to the target URL you'll have to extract that data first. Since the `processAsynchronously` method is only passed an ID of the note, you can use the `getNote(Long noteId, Converter<Note, T> converter)` method of the [NoteService](https://github.com/Communote/communote-server/blob/master/communote/persistence/src/main/java/com/communote/server/service/NoteService.java) to resolve the ID and get the data you want. With the help of the [ServiceLocator](https://github.com/Communote/communote-server/blob/master/communote/api/src/main/java/com/communote/server/api/ServiceLocator.java) you can get a reference of the NoteService like this: `ServiceLocator.findService(NoteService.class)`
- to ensure that your implementation of the `NoteStoringPostProcessor` interface is registered automatically to Communote when you deploy the plugin, you will have to add the following 3 annotations to the class:
  - org.apache.felix.ipojo.annotations.Component
  - org.apache.felix.ipojo.annotations.Instantiate
  - org.apache.felix.ipojo.annotations.Provides
- Now compile and build your plugin with Maven as described in the end of section 2.1.1 of the [How to Write a plugin](http://communote.github.io/doc/dev_how_plugin.html) tutorial.
- Install the created plugin as shown in the [installation documentation](http://communote.github.io/doc/install_extensions.html).

If you have further questions don't hesitate to ask 😃

**Comment by datenwort** [comment]
Thanks for this very detailed information. I will do my best to implement it.
