### ISSUE TITLE
Question: Extend user profile and admin page

### ISSUE THREAD

**Issue by datenwort** [Communote/communote-server#44]
Hi,

is it possible to extend the user profile (and all depending views) with additional fields? 
Or add a new item into the administration page?

BR

**Comment by rwi** [comment]
yes this should be possible with a [plugin](http://communote.github.io/doc/dev_how_plugin.html).
You can use properties which can be assigned to the core entities of Communote (like a user or topic) for storing the additional fields. A property is defined by 3 aspects: a key-group, a key and a value. The key-group should be a unique string which can be used for all the properties of your plugin. The key is a unique identifier within the key-group to differentiate the properties of your plugin. And the value, well, holds the value 😉 . The combination of key-group and key should avoid naming conflicts between properties of different plugins. For saving a property value you have to invoke the setObjectProperty Method of the [PropertyManagement](https://github.com/Communote/communote-server/blob/master/communote/api/src/main/java/com/communote/server/api/core/property/PropertyManagement.java). Please note that you have to register a property before it can be used by calling PropertyManagement.addObjectPropertyFilter. The PropertyManagement is a Spring service which can be accessed via [ServiceLocator.findService](https://github.com/Communote/communote-server/blob/master/communote/api/src/main/java/com/communote/server/api/ServiceLocator.java).

To see your fields in the views you could use JavaScript to fetch the properties via the REST API [property sub-resource](http://communote.github.io/generated/rest-api/gen/resources/user.html#Property_Resource) and inject them at the desired position. One of the views which shows user profile data is the AboutUserProfile widget. This widget is rendered on the page of a user (URL: /microblog/global/users/<login name>) in the profile tab.
To hook into the rendering of a widget you can listen for the lifecycle events of widgets by registering an event listener to the [WidgetController](https://github.com/Communote/communote-server/blob/master/communote/widgets/war/src/main/webapp/javascript/WidgetController.js). This is achieved by calling the `registerWidgetEventListener` method of the WidgetController instance which is exposed under `communote.widgetController`. The handler which needs to be passed to that method is a simple object with an `handleEvent` method. The event you should observe is `onWidgetInitComplete`. This event is always triggered after a widget was refreshed, that is, the HTML of the widget was loaded from the server and injected into the DOM. Your listener will be called with the name of the event and an object with details like the type of the refreshed widget (e.g. 'AboutUserProfileWidget') and its ID. The ID can be used to get the instance of the widget from the WidgetController (via `getWidget` method). The instance has a `domNode` member which holds the DOM element that contains the widget body and therefore allows injecting custom HTML at the right spot.
To ensure that the WidgetController instance is available at the time your JavaScript runs, you can add a callback to the [ApplicationInitializer](https://github.com/Communote/communote-server/blob/master/communote/webapp/src/main/webapp/javascript/init/ApplicationInitializer.js) which is available as `communote.initializer`. The `addWidgetFrameworkInitializedCallback` method is the one you should use for adding your callback.

If you need some hints for adding your fields to other views, don't hesitate to ask!

Extending the administration is possible too. The easiest way is to write a controller which extends from AdminstrationViewController as shown [here](https://github.com/Communote/communote-plugin-export/blob/master/src/main/java/com/communote/plugins/export/fe/admin/CreateExportController.java). The annotations on the class are responsible for creating the controller, registering it under a certain URL and adding an entry to the navigation section of the administration area.

**Comment by scrobbleme** [comment]
@datenwort @rwi 
I'm not sure, but I think you can use [PluginPropertyService ]( https://github.com/Communote/communote-server/blob/master/communote/plugins/communote-core-plugin/src/main/java/com/communote/plugins/core/services/PluginPropertyService.java), which just uses your plugin key as property key.

At least there was something like this planned. Don't know if we implemented it ;)

**Comment by rwi** [comment]
@scrobbleme yes we implemented it, but only for global (client and application) and not for entity properties 😉

**Comment by datenwort** [comment]
Hi,

I tried to follow your instructions. But I got an AuthorizationException, if I try to addObjectPropertyFilter

```
String symbolicName = bundleContext.getBundle().getSymbolicName();
PropertyManagement pm = ServiceLocator.findService(PropertyManagement.class);
pm.addObjectPropertyFilter(PropertyType.UserProperty, symbolicName, "KeyName");

try {
    StringProperty sp = pm.setObjectProperty(PropertyType.UserProperty, 0L, symbolicName, "KeyName, "bar");
    LOGGER.info("ATTRIBUTES: "+ sp.attributesToString());
} catch (NotFoundException e) {
    LOGGER.error("NotFoundException: " + e.getMessage() + e.getStackTrace().toString());
} catch (AuthorizationException e) {
    LOGGER.error("AuthorizationException: " + e.getMessage() + e.getStackTrace().toString());
}
```

I cannot set the object Property. Could you explain it a bit more?

**Comment by rwi** [comment]
The object properties allow storing individual property values per entity, that is in case of a user property you can store a different value for each user. This is how I understood your question.
If you want to show the same field value in every user profile, there are other ways to do it. If the value is static you could hard-code it, if it should be editable you could store it as a global (i.e. not link to an entity like a topic, user, note, etc.) client property with the help of the PluginPropertyService mentioned in one of the previous comments. For these properties you don't have to register an object property filter because they aren't object properties :wink:.

Some background on the AuthorizationException you are seeing: when assigning values to object properties there is typically an authorization check involved to ensure that the current user who modifies the properties is allowed to do so. The current user is the user currently logged in which triggered the operation. Example: there is a user property which holds the mobile phone number of a user. Since this is similar to any other profile field (like the name or the company) we enforce the same restrictions towards modification. That is, only the owner of the property/profile field, an admin or the internal system user can set or modify it. The internal system user is a special 'virtual' user who has permission to do nearly everything but can't login via the frontend and is instead intended for background tasks.
In your case the current user is unset (null) and therefore the modification of the property is not allowed and the exception is thrown. Does this help?

**Comment by datenwort** [comment]
@rwi I had the same understanding after trying to implement it. Based on the content replacement plugin i was able to do it. So now I try to show it in the profile view.

**Comment by datenwort** [comment]
If I store my additions within plugin properties, how can I connect to within the ```onWidgetInitComplete``` event?

**Comment by rwi** [comment]
You could fetch your plugin properties with an AJAX request before the widget is rendered. For this you need a controller on the server side and some JavaScript on the client side.
The controller is straight forward:
* add a class to your plugin which implements the interface [org.springframework.web.servlet.mvc.Controller](https://docs.spring.io/autorepo/docs/spring-framework/3.2.8.RELEASE/javadoc-api/org/springframework/web/servlet/mvc/Controller.html)
* add the following annotations to this class which will take care of automatic registration of the controller when your plugin is deployed:
  * org.apache.felix.ipojo.annotations.Component
  * org.apache.felix.ipojo.annotations.Provides
  * org.apache.felix.ipojo.annotations.Instantiate
  * [com.communote.plugins.core.views.annotations.UrlMapping](https://github.com/Communote/communote-server/blob/master/communote/plugins/communote-core-plugin/src/main/java/com/communote/plugins/core/views/annotations/UrlMapping.java)
    * this annotation defines the URL of your controller and should look like this `@UrlMapping("/*/somethingUniqueToAvoidConflictsWithOtherPlugins/yourResource")` (the * is required, the rest is up to you). The controller will be accessible at your-servername:port/microblog/global/somethingUniqueToAvoidConflictsWithOtherPlugins/yourResource
 * the `PluginPropertyService` can be injected with the `Requires` annotation as shown above
 * the handleRequest method of the controller doesn't have to return a ModelAndView, you can also handle the request directly and for example write stringified JSON to the response. In case you want to return JSON, you could use the [JsonHelper](https://github.com/Communote/communote-server/blob/master/communote/api/src/main/java/com/communote/server/api/util/JsonHelper.java) or the [JsonRequestHelper](https://github.com/Communote/communote-server/blob/master/communote/webapp/src/main/java/com/communote/server/web/commons/helper/JsonRequestHelper.java).

On the client side you can trigger the AJAX request in a callback added to the ApplicationInitializer (e.g. via the `addWidgetFrameworkInitializedCallback` method) as described in my previous comment. In the success callback of your AJAX request you can check whether the widget is already refreshed and inject your HTML or store the plugin properties in a variable and wait until the lifecycle event is fired. But please don't listen for the `onWidgetInitComplete` event, use `onWidgetRefreshComplete` instead. I inserted the wrong name in my previous answer :blush: (I corrected it just now).


If you want to make sure that the widget is not rendered before your AJAX request returns you can define an initialization condition for a specific widget. This can be done with the `addWidgetInitCondition` method of the [WidgetController](https://github.com/Communote/communote-server/blob/master/communote/widgets/war/src/main/webapp/javascript/WidgetController.js) (see also JsDoc of this method) and would look like this for the AboutUserProfileWidget mentioned above:

```javascript
// define the condition in the ApplicationInitializer callback where you start your request
communote.widgetController.addWidgetInitCondition('AboutUser', 'myPluginPropertiesAreLoaded');

// fulfil the condition in the success callback of your AJAX request after saving the plugin properties in a suitable variable
communote.widgetController.widgetInitConditionFulfilled('AboutUser', 'myPluginPropertiesAreLoaded');
```

**Comment by datenwort** [comment]
Thank you for all the help. Now it works like expected. But every solutions lead to new questions.

I would like to store the entered values. Please correct me if I think in the wrong way. 

1. Have to listen to the submit event (Is there a special event to follow the submission of the ```userprofiledetails_form```? An eventlistener on the submit event will not work.)
2. Add properties to a user to store it.

Is there something I need to consider?

**Comment by rwi** [comment]
Yes you're thinking in the right way. The problem is the first step because the form isn't submitted. Instead, the widget sends an AJAX POST request which includes the data of the form. The server modifies the user data and responses the request with the updated widget HTML which replaces the old HTML. The `onWidgetRefreshComplete` event is fired afterwards.

Sadly, no special event is triggered before or after the submit. But you could overwrite the `submit` method in the widget instance. This method is inherited from the [FormWidget](https://github.com/Communote/communote-server/blob/master/communote/widgets/war/src/main/webapp/javascript/FormWidget.js) class and is responsible for starting the POST request.
With overwriting I mean something like this (untestet :wink: )

```javascript
var widget = communote.widgetController.getWidget(widgetId);
var orgSubmit = widget.submit;
widget.submit = function() {
    // show that the widget is doing something
    this.startLoadingFeedback();
    // send your data to your controller which saves the properties for the current user (your step 2). If you only have to store one property per user you could use the property sub-resource of the user resource of the rest API.
    // after this request succeeded trigger the actual submit of the widget which stops the loading feedback when everything is done
    return orgSubmit.apply(this, arguments);
};
```
A good place for doing this is the event handler of the `onWidgetInitComplete` lifecycle event of the UserProfileDetails widget. This event is only fired once when the widget is initialized and before it is refreshed for the first time.

The downside of this solution is that it is a bit hacky and the update of the user data needs two individual requests. If the second fails for whatever reason, you have a partially updated user profile which isn't that great from the user's perspective. I guess it would be better if we extend the widget in Communote's core and 

* add a method getUserProperties() to the JavaScript part of the widget which returns an array with the user properties. The server has to provide the data when the widget is refreshed.
* fire an onBeforeSubmit event in every FormWidget. An event handler could add user properties to the array.
* send the properties with other form data and update them on the server side in the same transaction which is used for modifying the profile.

The mechanism of the interests textbox uses two components. The first is the [TextboxList](https://github.com/Communote/communote-server/blob/master/communote/webapp/src/main/webapp/javascript/textboxlist/TextboxList.js) which creates and manages the button like items in the input. The 2nd is the [Autocompleter](https://github.com/Communote/communote-server/blob/master/communote/webapp/src/main/webapp/javascript/autocompleter/Autocompleter.js) which loads and shows the suggestions matching the user input. Both are constructed with 2 arguments where the 1st is an input element (or CSS selector) and the 2nd an object with options. For details on the available options and methods of these classes please have a look at the JsDoc found in the JavaScript files. For the Autocompleter there is also an [AutocompleterFactory](https://github.com/Communote/communote-server/blob/master/communote/webapp/src/main/webapp/javascript/autocompleter/AutocompleterFactory.js) which can be used for initializing generic or common completers or as a source of inspiration :wink: .
The Autocompleter classes and the factory are available in the global scope, the TextboxList constructor is in the `communote.classes` namespace.

**Comment by datenwort** [comment]
Just one last question before finalizing the project. I register UserProperties via ```addObjectPropertyFilter``` to fill them later with values. This works like expected. But now I am facing an issues that after a restart of communote this registrations seems to be missing. Values cannot be read from the UserProperties List. So is there something I am missing?

**Comment by rwi** [comment]
Good to hear you got it working :smiley: 

Where are you calling `addObjectPropertyFilter`? A good place would be the activator of your plugin because it's invoked every time when the plugin is activated by the OSGi runtime. If you don't remove the plugin from the plugin directory it should be activated automatically when Communote starts.

The registration of these property filters is a pure runtime feature and not persisted. So you have to do it every time the plugin is activated and consequently unregister them when the plugin stops (e.g. because of removing it from the plugin directory).

**Comment by datenwort** [comment]
I did it indeed in the ```Activator.java```. Unfortunately I do not get the ```PluginPropertyService```running. I got a NullPointerException. It seems it is not instantiated in this stage.

```
@Requires
private PluginPropertyService pluginPropertyService;

String clientValues = pluginPropertyService.getClientProperty(symbolicName);
````

I also tried to use the ```PluginPropertyManagement```. But it does not found any values for the symbolicName.

Any hints?

**Comment by rwi** [comment]
An activator defined in the pom.xml is an OSGi feature. The Requires annotation on the other hand is an [iPOJO](http://felix.apache.org/documentation/subprojects/apache-felix-ipojo.html) feature. iPOJO is built on top of OSGi and the annotations can only be used in iPOJO components and services, which the activator isn't.
However, using the PluginPropertyManagement in your activator should work. Please check that you are invoking the getClientProperty method correctly: `ServiceLocator.findService(PluginPropertyManagement.class).getClientProperty(symbolicName, key, defaultValue)`. The `symbolicName` is the return value of `org.osgi.framework.Bundle.getSymbolicName()`. An instance of the bundle is injected as argument into the constructor of the activator. The `key` is the key you used for storing the property. The `defaultValue` can be null.

But after rereading your [previous comment](https://github.com/Communote/communote-server/issues/44#issuecomment-373350344), I'm a bit confused. There you mentioned you have problems accessing the UserProperties. These properties and the property filters are part of the `PropertyManagement` and not the `PluginPropertyManagement` (I know quite similar these names :wink:). Maybe you have mixed something?

**Comment by datenwort** [comment]
The ```PropertyManagement``` is to store properties for different entities. 
The ```PluginPropertyService``` to register and unregister property entities.

In the ```Activator``` the call ```pluginPropertyService.getClientProperty("whatever")```throws a ```NullPointerException```. In my AdminController and the Controller this call works.

I tried to get the properties by calling ```pluginPropertyManagement.getAllClientProperties("whatever")```. But this also fails.

**Comment by datenwort** [comment]
An additional question to the tag management. I can store them via 

```
TagManagement tm = ServiceLocator.instance().getService(TagManagement.class);
TagTO t = new TagTO(tag, TagStoreType.Types.ENTITY);

if (tm.findTag(tag, TagStoreType.Types.ENTITY) == null)
{
	tm.storeTag(t);
}
```

But how to add them that they are shown in the autocompleter and the tag cloud. I know that they have to appear in the core_entity2tags database table.

**Comment by rwi** [comment]
To address your [previous question](https://github.com/Communote/communote-server/issues/44#issuecomment-374127309):

> The `PropertyManagement` is to store properties for different entities.

Exactly. Registering (and unregistering) a filter which allows the usage of a new property (defined by key group and key) together with a specific type of entity (user, topic, note, ...) is also part of this class (`addObjectPropertyFilter` method). Adding such a filter is always the prerequisite before a property can be stored for an entity.

> The `PluginPropertyService` to register and unregister property entities.

Not quite sure what you mean, but the purpose of the `PluginPropertyService` is providing an interface for storing settings for your plugin. These settings resemble the entity properties which means they have a key group, a key and a value. That's why we use the term 'property'. In contrast to the entity properties managed by the `PropertyManagement` these properties are not assigned to entities but are more like general or global settings. To ensure that they belong to a specific plugin we set the key group to something identifying the plugin. Since every plugin is an OSGi bundle and each bundle has a unique symbolic name the `PluginPropertyService` takes this symbolic name for it. So whenever you are invoking `PluginPropertyService.setClientProperty(key, value)` you're actually creating or editing a property with:
* key group set to the symbolic name of your plugin
* key set to the provided key and
* value set to the given value.

To round things up: the `PluginPropertyService` is an iPOJO compatible and bundle aware facade to the `PluginPropertyManagement`. iPOJO compatible means it can be used in iPOJO components and services. Bundle aware means that it knows the bundle and its symbolic name when it is injected in an iPOJO component or service via the Requires annotation. So nearly all methods of the `PluginPropertyService` have no argument for the symbolic name (key group of the property). The methods of the `PluginPropertyManagement` on the other hand have. The `PluginPropertyService` delegates all calls to the `PluginPropertyManagement` and passes the known symbolic name (i.e. `PluginPropertyService.setClientProperty(key, value)` invokes `PluginPropertyManagement.setClientProperty(symbolicNameOfYourBundle, key, value)`)

> In the Activator the call `pluginPropertyService.getClientProperty("whatever")` throws a `NullPointerException`. In my AdminController and the Controller this call works.

Your AdminController is an iPOJO component (Component annotation on the class), that's why the dependency defined by the Requires annotation is injected. Your Activator is a pure OSGi feature and not an iPOJO component or service. Therefore the Requires annotation isn't evaluated, the service isn't injected and will be null. You have to use the `PluginPropertyManagement` there.

> I tried to get the properties by calling `pluginPropertyManagement.getAllClientProperties("whatever")`. But this also fails.

Yes it has to, because you are passing the key and not the symbolic name (key group) to the method (see JavaDoc of method). To get your property with key "whatever" you can call `pluginPropertyManagement.getClientProperty(symbolicName, "whatever", null)` or `pluginPropertyManagement.getAllClientProperties(symbolicName).get("whatever")` (since this method returns a map with all key-value pairs of the properties belonging to your plugin). The `symbolicName` is the return value of `org.osgi.framework.Bundle.getSymbolicName()`. An instance of the bundle is passed as argument into the constructor of the Activator.

**Comment by rwi** [comment]
@datenwort regarding your [question](https://github.com/Communote/communote-server/issues/44#issuecomment-374396446) about storing tags: you don't have to use the `TagManagement` directly. It's suffice to invoke `UserManagement.updateUserTags(Long userId, Set<TagTO> tags)` because this method will create any non-existing tag automatically. The preferred way for creating the TagTO is by using the second constructor: `new TagTO(tag, TagStoreType.Types.ENTITY.getDefaultTagStoreId())`.

Please be aware, that `updateUserTags` replaces the tags of a user. If you only want to add additional tags, you'll have to load the existing first and put them together with your new ones into the set.
The tags of a user can be retrieved by invoking `UserManagement.getUserById(userId, converter)` and passing a converter which includes the tags. A converter which does this is [UserToUserDataConverter](https://github.com/Communote/communote-server/blob/master/communote/persistence/src/main/java/com/communote/server/core/converter/user/UserToUserDataConverter.java). Alternatively you can write your own small converter which just fetches the tags:

```java
import java.util.HashSet;
import java.util.Set;
import com.communote.common.converter.Converter;
import com.communote.server.api.core.tag.TagTO;
import com.communote.server.model.tag.Tag;
import com.communote.server.model.user.User;

public class TagExtractingConverter implements Converter<User, Set<TagTO>> {

    @Override
    public Set<TagTO> convert(User source) {
        HashSet<TagTO> tags = new HashSet<>();
        if (source.getTags() != null) {
            for (Tag tag : source.getTags()) {
                tags.add(new TagTO(tag.getDefaultName(), tag.getTagStoreAlias()));
            }
        }
        return tags;
    }
}
```

**Comment by datenwort** [comment]
So next construction issue ;)

The updateUserTags function does not work as expected. I create a HashSet with all the TagTOs.

```
HashSet<TagTO> tagTOs = new HashSet<TagTO>();

tagTOs.clear();

for(String tag: tags.split(", ")) 
{
	if (!tag.isEmpty())
	{
		TagTO t = new TagTO(tag, TagStoreType.Types.ENTITY.getDefaultTagStoreId());
		tagTOs.add(t);
	}
}
```

And try to store them with

```
UserManagement um = ServiceLocator.instance().getService(UserManagement.class);
um.updateUserTags(SecurityHelper.getCurrentUserId(), tagTOs);
```

The tagTOs set contains all data I want to add, but unfortunately the update will not work. New tags will be added to the ```core_tag``` table. But the connection to the user in table ```core_entity2tags``` will not be updated. Any clue why?

**Comment by rwi** [comment]
Hmm, actually this should work. Do you see any errors or warnings in the logs? Can you add tags to this user with the normal edit profile form or does this fail too?

**Comment by datenwort** [comment]
this works without any problem. Just the update command.

**Comment by rwi** [comment]
This should work with 3.5-SNAPSHOT.

Is your code, which tries to update the tags, triggered by the submit of the UserProfileDetails widget as we discussed [earlier](https://github.com/Communote/communote-server/issues/44#issuecomment-370626443)? If so, maybe the two operations interfere with each other, like so:

* the form is saved and your overwritten submit method is called
* your Controller is invoked and stores everything as expected
* after this request has completed the original submit method of the widget is invoked and saves the profile data including the tags. The tags that are stored are those found in the input field of the form and they will replace all existing tags. If the field is empty all tags will be removed. The tags saved by your Controller would be lost.

**Comment by datenwort** [comment]
Is there a nicer solution than replacing the widget.serializeForm values to store the tags?

**Comment by rwi** [comment]
Maybe you could add your tags to the original tag input element?

**Comment by datenwort** [comment]
Created a working update of the Profile page
