### ISSUE TITLE
Theme Plugins for login screen

### ISSUE THREAD

**Issue by datenwort** [Communote/communote-server#46]
Hi,

just to get to know if I should further explorer why the login screen cannot be modified by my theme plugin. Is it still possible to modify it?

**Comment by scrobbleme** [comment]
Generally it should be possiible as you may only need to replace the used Velocity files. At least I think it should work this way.
Have you put the files into `/src/main/resources/META-INF/resources/vm/login/` within your plugin?

**Comment by datenwort** [comment]
No I just want to change the CSS files, so I modified the layout-tiny.css which I found in the html dom. But the CSS is not used.

**Comment by scrobbleme** [comment]
I don't think it is possible to override CSS files.

You may add your own CSS file which overwrites the original rules. This should be loaded after the original files.

**Comment by datenwort** [comment]
Overwriting by creating a plugin which contains css files with the same css selectors. So that works, but only after login. Not for the login screen itself.

**Comment by scrobbleme** [comment]
See the smileys plugin on how to add custom CSS: https://github.com/Communote/communote-server/tree/master/communote/plugins/communote-smileys-plugin/src/main/resources/META-INF

You need a css-categories.json and the css file. Instead of "portal" you should be able to use "[login](https://github.com/Communote/communote-server/blob/master/communote/webapp/src/main/webapp/WEB-INF/vm/login/login_page.html.vm)"

**Comment by datenwort** [comment]
Hi, thanks for the help. Portal is working fine for the other css files, but login will not be used. 
The possible modes are ```HTML, PLAIN, PORTAL, REPOST, REPOST_PLAIN```

**Comment by datenwort** [comment]
I think I found the identifier. It is ```layout-tiny```
