### ISSUE TITLE
Question: What is the difference in the plugin status installed and activ?

### ISSUE THREAD

**Issue by datenwort** [Communote/communote-server#47]
Hi,

what is the difference in the plugin status installed and activ?
Everytime I try to implement an own NotificationService the plugin will not be activated. There is no errors in the log...So I am a bit confused.

**Comment by rwi** [comment]
With "status" you probably refer to the "status" column of the extension overview in Communote's administration section, right? If so, then the status reflects the state of the OSGi bundle (a Communote plugin is an OSGi bundle) in the [OSGi life cycle](https://www.packtpub.com/books/content/osgi-life-cycle). A bundle transitions from _installed_ over _resolved_ and _starting_ to _active_. If your bundle doesn't enter the active state, then you might be missing some dependencies.

Do you have an activator? Is it called?
How did you implement your NotificationService (e.g. as an iPOJO component)? Could you share some code so we can have a look?

Btw. a good way for analysing OSGi related problems is to connect to an OSGi shell of the OSGi runtime. There you can check for missing dependencies or try to start a bundle and look for caused errors. Since Communote uses Felix as OSGi runtime you can use the [Felix OSGi Shell](http://felix.apache.org/documentation/subprojects/apache-felix-shell.html) and the [Felix Remote Shell](http://felix.apache.org/documentation/subprojects/apache-felix-remote-shell.html) for this. Both are OSGi bundles which can be downloaded from [here](http://felix.apache.org/downloads.cgi) and just need to be dropped into Communote's plugin directory.

**Comment by datenwort** [comment]
Thanks for the information. I will try the shell to evaluate my plugin. Afterwards I will post the information on here. 

Currently I have an Activator and a single class just with logging information. But none of them seems to be called. But I will see what the analyse will bring.

**Comment by datenwort** [comment]
Hi

so I need additional help. Please find attached the source code, which is just as simple as it could be.

Activator.java
```
package com.communote.plugins;

import org.osgi.framework.BundleActivator;
import org.osgi.framework.BundleContext;

import org.slf4j.LoggerFactory;

import org.slf4j.Logger;

public class Activator implements BundleActivator 
{
	private static Logger LOGGER = LoggerFactory.getLogger(Activator.class);

    public void start(BundleContext context)
    {
    	LOGGER.info("Start");
    }

    public void stop(BundleContext context)
    {
    	LOGGER.info("Stop");
    }
}
```

TestNotePostProcessor
```
package com.communote.plugins.test;

import com.communote.common.util.Orderable;
import com.communote.server.api.core.note.NoteStoringTO;
import com.communote.server.api.core.note.processor.NoteStoringPostProcessorContext;
import com.communote.server.core.blog.notes.processors.UserNotificationNoteProcessor;
import com.communote.server.model.note.Note;

import java.util.Map;

import org.apache.felix.ipojo.annotations.Component;
import org.apache.felix.ipojo.annotations.Instantiate;
import org.apache.felix.ipojo.annotations.Provides;

import org.slf4j.LoggerFactory;
import org.slf4j.Logger;

@Component
@Instantiate(name = "TestNotePostProcessor")
@Provides
public class TestNotePostProcessor extends UserNotificationNoteProcessor implements Orderable {

       private static Logger LOGGER = LoggerFactory.getLogger(TestNotePostProcessor .class);

	@Override
	public int getOrder() {
		return 10001;
	}
	
	@Override 
	public boolean process(Note note, NoteStoringTO orginalNoteStoringTO,
            Map<String, String> properties) {
		LOGGER.info("TestNotePostProcessor process");
		return false;
	}
	
     @Override
     public void processAsynchronously(Long noteId, NoteStoringPostProcessorContext context) {
		LOGGER.info("TestNotePostProcessor processAsynchronously");
	}
}
```

**Comment by scrobbleme** [comment]
@datenwort Can you share you pom.xml?

The activator has to be set there, see at maven-bundle-plugin: https://github.com/Communote/communote-server/blob/master/communote/plugins/communote-ldap-plugin/pom.xml

**Comment by datenwort** [comment]
I think I have found the problem. Taking a look within the pom.xml I saw that instead of version 3.4 3.5-SNAPSHOT is referenced. With this a new function has to be implemented ```getID```. If I change the reference to 3.5-SNAPSHOT and add this function everything works like expected.
